### ISSUE TITLE
执行的效率问题

### ISSUE THREAD

**Issue by BaroneX** [CoderJackyHuang/HYBUnicodeReadable#1]
这样做,在输出大段结构复杂的字符的时候,可能会影响.不过 还是 很方便.赞一个

**Comment by CoderJackyHuang** [comment]
请不要在意效率问题，因为这只是在DEBUG模式下使用就可以了

原始邮件
发件人:BLAKEnotifications@github.com
收件人:CoderJackyHuang/HYBUnicodeReadableHYBUnicodeReadable@noreply.github.com
发送时间:2016年1月5日(周二) 10:41
主题:[HYBUnicodeReadable] 执行的效率问题 (#1)

这样做,在输出大段结构复杂的字符的时候,可能会影响不过 还是 很方便赞一个

**Comment by BaroneX** [comment]
bingo!
