### ISSUE TITLE
打印字符串的问题

### ISSUE THREAD

**Issue by 0x5e** [CoderJackyHuang/HYBUnicodeReadable#2]
是否需要转义一下?原先打印出来的是会转义过的
只是调试看看倒是没什么问题..就是觉着有些怪

**Comment by CoderJackyHuang** [comment]
不用的，其实我只是重写了这个方法，里面只是增加一些特殊处理而已

原始邮件
发件人:gaosennotifications@github.com
收件人:CoderJackyHuang/HYBUnicodeReadableHYBUnicodeReadable@noreply.github.com
发送时间:2016年1月29日(周五) 19:34
主题:[HYBUnicodeReadable] 打印字符串的问题 (#2)

是否需要转义一下?原先打印出来的是会转义过的
 只是调试看看倒是没什么问题..就是觉着有些怪
